# The paths are relative to the 'cad_models_additional_search_path' param
# positions are in meters and orientations in radians
- id: "env"
  label: "background"
  description: "walls"
  file: "urdf/adream_empty.urdf"
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "door_h20"
  label: "door"
  description: "door"
  file: "urdf/door_h20.urdf"
  position:
    x: -0.05
    y: 14.757
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "elevator_1"
  label: "elevator"
  description: "elevator"
  file: "urdf/elevator_1.urdf"
  position:
    x: -7.524
    y: 11.470
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "stairs_1"
  label: "stairs"
  description: "stairs"
  file: "urdf/stairs_1.urdf"
  position:
    x: -2.550
    y: 12.744
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "appartment"
  label: "appartment"
  description: "appartment"
  file: "urdf/appartment.urdf"
  position:
    x: 5.467
    y: 10.399
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "toilet_door"
  label: "door"
  description: "toilet's door"
  file: "urdf/simple_door.urdf"
  position:
    x: -9.212
    y: 14.302
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: -0.9
- id: "door_h10"
  label: "door"
  description: "door"
  file: "urdf/glass_door.urdf"
  position:
    x: -5.83
    y: 19.78
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 2.2
- id: "door_h14"
  label: "door"
  description: "door"
  file: "urdf/simple_door.urdf"
  position:
    x: -6.576
    y: 9.800
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "door_h16"
  label: "door"
  description: "door"
  file: "urdf/basic_door.urdf"
  position:
    x: -0.196
    y: 22.420
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "door_h21"
  label: "door"
  description: "door"
  file: "urdf/basic_door.urdf"
  position:
    x: 0.544
    y: -0.009
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.57
- id: "door_h22"
  label: "door"
  description: "door"
  file: "urdf/basic_door.urdf"
  position:
    x: 4.648
    y: 18.475
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.57
- id: "door_h23"
  label: "door"
  description: "door"
  file: "urdf/basic_door.urdf"
  position:
    x: 0.507
    y: 18.443
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 1.57
- id: "glass_door_h20_1"
  label: "glass_door"
  description: "door"
  file: "urdf/glass_door.urdf"
  position:
    x: 11.545
    y: 15.977
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "glass_door_h20_2"
  label: "glass_door"
  description: "door"
  file: "urdf/glass_door.urdf"
  position:
    x: 11.545
    y: 6.004
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "glass_door_h20_3"
  label: "glass_door"
  description: "door"
  file: "urdf/glass_door.urdf"
  position:
    x: 11.545
    y: -3.851
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "hanger"
  label: "hanger"
  description: "hanger"
  file: "urdf/hanger.urdf"
  position:
    x: 5.5
    y: 6
    z: 0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "hat"
  label: "hat"
  description: "hat"
  file: "urdf/hat.urdf"
  position:
    x: 5.5
    y: 6
    z: 0.52
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "table1"
  label: "table"
  description: "table1"
  file: "urdf/table.urdf"
  position:
    x: 3.5
    y: 7.2
    z: 0.4
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "teapot"
  label: "teapot"
  description: "teapot"
  file: "urdf/teapot.urdf"
  position:
    x: 3.5
    y: 7.2
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "milk"
  label: "milk"
  description: "milk"
  file: "urdf/milk.urdf"
  position:
    x: 3.5
    y: 7.4
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "mug"
  label: "mug"
  description: "mug"
  file: "urdf/mug.urdf"
  position:
    x: 3.7
    y: 7.4
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0

- id: "mug2"
  label: "mug"
  description: "mug"
  file: "urdf/mug.urdf"
  position:
    x: 3.9
    y: 7.2
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0

- id: "mug3"
  label: "mug"
  description: "mug"
  file: "urdf/mug.urdf"
  position:
    x: 3.4
    y: 7.6
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
- id: "mug4"
  label: "mug"
  description: "mug"
  file: "urdf/mug.urdf"
  position:
    x: 3
    y: 7
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0

- id: "book"
  label: "book"
  description: "book"
  file: "urdf/book.urdf"
  position:
    x: 2.7
    y: 5.55
    z: 0.78
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0


- id: "table2"
  label: "table"
  description: "table1"
  file: "urdf/table.urdf"
  position:
    x: 2.90
    y: 5.75
    z: 0.4
  orientation:
    x: 0.0
    y: 0.0
    z: 1.570


- id: "laptop"
  label: "laptop"
  description: "laptop"
  file: "urdf/laptop.urdf"
  position:
    x: 3.2
    y: 6.1
    z: 0.82
  orientation:
    x: 0.0
    y: 0.0
    z: 0

- id: "shelf"
  label: "shelf"
  description: "shelf"
  file: "urdf/shelf.urdf"
  position:
    x: 1.6
    y: 6.1
    z: 0.38
  orientation:
    x: 0.0
    y: 0.0
    z: 1.57

- id: "clock"
  label: "clock"
  description: "clock"
  file: "urdf/clock.urdf"
  position:
    x: 2.9
    y: 9
    z: 1.7
  orientation:
    x: 0
    y: 0
    z: 0
